### ISSUE TITLE
Create Optimizely variants for Remix button in on-boarding experience

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker.org#1082]
Let's test the button new users will push in their first step of the on-boarding experience.

A list of options from #1070:

- Get Started
- Go
- Next
- Make
- Remix

**Comment by secretrobotron** [comment]
@ScottDowne @simonwex @adamlofting @gesa  if we want to test this, I think we'll run into the Optimizely+Angular problem again, won't we?

**Comment by gesa** [comment]
I think we need to wait until the current Optimizely test (with the five variants of home) is done before we can build another. Remember, each variant requires an entire new version of the relevant page to be built.

**Comment by gesa** [comment]
I'd really like to take the time to pull angular out of the home page next heartbeat, so we can implement this test!

**Comment by adamlofting** [comment]
@gesa +1 to getting angular out of the homepage if we can. It will allow much more iterative testing.

**Comment by ScottDowne** [comment]
I'm not familiar with the optimizely + angular problem. Are we not already AB testing home pages?

**Comment by adamlofting** [comment]
@ScottDowne - we're currently doing it in a more tedious way by creating multiple copies of the page and only using Optimizely to manage the flow of traffic. Ideally we can use Optimizely to modify content on the fly.

There's some history of the issue in this bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1053817
