### ISSUE TITLE
Background on dark blue area is pixelated/doesn't fill entire width

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker.org#1340]
![image](https://cloud.githubusercontent.com/assets/1455535/6404190/55c92a66-bde3-11e4-8c11-acffb778e513.png)

**Comment by mmmavis** [comment]
heh good catch @k88hudson 
I noticed the same thing when I was building the page but it turned out that "gap" was part of the [image itself] (https://webmaker.org/img/moi/moi-video-preview.png) :p 
We'll have to replace that placeholder image when the **real video** is ready (it'll just be a screencap from the video)

**Comment by k88hudson** [comment]
Ah cool! feel free to close the issue then

**Comment by mmmavis** [comment]
Thanks for QAing :dancers:
