### ISSUE TITLE
Remove Privacy Eye and Banner

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker.org#1385]
Wondering two things: 
* what has the effect of the eyeball been on our homepage conversion metrics?
* when we are supposed to remove the freaky eyeball and Privacy banner? Privacy Day is over afaik? Do we have something to replace that content with or can we go back to our generic homepage?

cc/ @HPaulJohnson @adamlofting @thisandagain

**Comment by adamlofting** [comment]
A few notes from me
* We never tested adding this in a structured way, so we don't have data on the impact.
* We talked about doing a structured test to remove this (i.e. hide it for 50% of traffic before removing it completely), but there were other higher priorities at the time (I think shipping the app) so we decided not too this time
* There was no dramatic shift in the overall conversion KPI, so this didn't have a big impact
  * But my hunch is it will slightly reduce conversion because it splits the users' focus - that's just a hunch for now though
* I've spent more time talking to people about if and how this should be removed than it would have taken to remove it :stuck_out_tongue_winking_eye: 
* This task is an example of something that falls through the Plan (aka TPS) process. As there's not a good way to schedule an hour of work that isn't linked to a P1
  * But this is hopefully covered by the new plan to allocate a dev and designer to these smaller tasks each sprint

My view: generally, the homepage CTA for a cold audience should be as simple and clear as possible (i.e. sign up). And thematic content like this is better suited to a warm audience (i.e. after people login).

**Comment by HPaulJohnson** [comment]
Plan Issue https://github.com/MozillaFoundation/plan/issues/352 has been open since 2/18 in attempt to get this removed.

**Comment by cassiemc** [comment]
Thanks for the info guys. Let's try to add this as a task to https://github.com/MozillaFoundation/plan/issues/390. 

I'm going to close this issue since https://github.com/MozillaFoundation/plan/issues/352 already exists. 

cc @simonwex for context
